version: '3.8'

services:
    app:
        image: todolist-app-server
        build:
            context: .
            dockerfile: Dockerfile
        restart: on-failure
        environment:
            DB_HOST: db
        ports:
            - "3000:3000"
        depends_on:
            - db

    db:
        image: 'postgres:16.1'
        restart: no
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: todos
        ports:
            - '5432:5432'
        volumes:
            - postgres-data-react-native-golang-todolist-app:/var/lib/postgresql/data/

volumes:
    postgres-data-react-native-golang-todolist-app:
