version: '3.8'

services:
    db:
        image: 'postgres:16.1'
        restart: no
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: todos
        ports:
            - '5432:5432'
        volumes:
            - postgres-data-react-native-golang-todolist-app:/var/lib/postgresql/data/

volumes:
    postgres-data-react-native-golang-todolist-app:
