run-postgres:
	docker-compose up db

build:
	docker build -t todolist-app-server .

run:
	docker-compose up -d

stop:
	docker-compose stop

remove:
	docker-compose down

logs:
	docker-compose logs -f
